var English = {
    "Ask Me Bet": "Ask Me Bet",
    "Askmebet": "Askmebet",
    "Close": "Close",
    "Guide": "<i class='fas fa-guide'></i>&nbsp;Guide",
    "Chat Bot": "Chat Bot",
    "Search User": "Search User",
    "Pretty Gaming": "Pretty Gaming",
    "Super Slot": "Super Slot",
    "Football": "Football",
    "Lotto": "Lotto",
    "Ambbet": "Ambbet",
    "missing 'Username' field": "Please enter your 'Username'.",
    "missing 'Password' field": "Please enter your 'Password'.",
    "missing 'Contact' field": "Please enter 'Contact'.",
    "missing 'Level' field": "Please select 'Level'.",
    "Save": "Save",
    "Add new member success.": "Add new member success.",
    "Username is duplicate.": "Username is duplicate.",
    "Delete Member": "Delete Member",
    "Delete member success.": "Delete member success.",
    "Edit member success.": "Edit member success.",
    "Login failed.": "Login failed. Please try again.",
    "Please select type.": "Please select type.",
    "Please select agent.": "Please select agent.",
    "Please enter bet ID.": "Please enter bet ID.",
    "Cancel bet ID success.": "Cancel bet ID success.",
    "Add new dashboard success.": "Add new dashboard success.",
    "missing 'Product' field": "Please enter your 'Product'.",
    "missing 'Agent' field": "Please enter your 'Agent'.",
    "missing 'Attach file' field": "Please select 'Attach file'.",
    "missing 'Start date' field": "Please enter your 'Start date'.",
    "missing 'To date' field": "Please enter your 'To date'.",
    "missing 'Description' field": "Please enter 'Description'.",
    "Add new leave success.": "Add new leave success.",
    "Approve this leave success.": "Approve this leave success.",
    "Reject this leave success.": "Reject this leave success.",
    "missing 'Search' field": "Please enter 'Bet ID' or 'Username'.",
    //
    "OK": "OK",
    "Mobile Version": "<i class='fas fa-mobile'></i>&nbsp;Mobile Version",
    "Incorrect Username or Password, Please try Again.": "Incorrect Username or Password, Please try Again.",
    "Incorrect Username": "Account is Inactive, Please Contact Admin.",
    "Contact your associate in case you forgot the password or unable to sign in": "Contact your associate in case you forgot the password or unable to sign in",
    "Username": "Username",
    "Username_": "Username<label style='color: red;'>&nbsp;*</label>",
    "Password": "Password",
    "Password_": "Password<label style='color: red;'>&nbsp;*</label>",
    "Sign in": "Sign in",
    "Log Out": "<i class='fas fa-sign-out-alt'></i>&nbsp;Log Out",
    "Dashboard": "Dashboard",
    "Quotation List": "Quotation List",
    "Quotation No": "Quotation No",
    "Upload Silp": "Upload Silp",
    "PDF File": "PDF File",
    "Slip": "Slip",
    "Upload": "Upload",
    "Member": "Member",
    "Member List": "Member List",
    "Please enter search.": "Please enter search.",
    "Search": "Search",
    "Search-": "Search :",
    "First name/Last name": "First name / Last name",
    "Select": "Select",
    "All": "All",
    "No.": "No.",
    "First Name": "First Name",
    "Last Name": "Last Name",
    "Nickname": "Nickname",
    "Role": "Role",
    "Role_": "Role<label style='color: red;'>&nbsp;*</label>",
    "Status": "Status",
    "Status-": "Status :",
    "Status_": "Status<label style='color: red;'>&nbsp;*</label>",
    "missing 'Status' field": "Please select 'Status'.",
    "Last login date": "Last login date",
    "Active": "Active",
    "Inactive": "Inactive",
    "Report": "Report",
    "Master Form": "Master Form",
    "Master Form-": "Master Form :",
    "Master Form_": "Master Form<label style='color: red;'>&nbsp;*</label>",
    "Create Form": "Create Form",
    "Dashboard Report": "Dashboard Report",
    "Add Master Form_": "<i class='fas fa-plus mr-1;'></i>Add Master Form",
    "Add Master Form": "Add Master Form",
    "to": "to",
    "Start date-": "Start date :",
    "To date-": "To date :",
    "Start date": "Start date",
    "End date": "End date",
    "To date": "To date",
    "missing 'Start-To Date' field": "'To date' must greater than 'Start date'.",
    "Basic Info": "Basic Info",
    "Form Name_": "Form Name<label style='color: red;'>&nbsp;*</label>",
    "Form Name": "Form Name",
    "Company Name_": "Company Name<label style='color: red;'>&nbsp;*</label>",
    "Company Name": "Company Name",
    "Company Name-": "Company Name :",
    "Create": "Create",
    "Discard": "Discard",
    "Transaction": "Transaction",
    "Add/Edit Transaction": "Add/Edit Transaction",
    "Add/Edit Master Form": "Add/Edit Master Form",
    "My task": "My task",
    "Revenue": "Revenue",
    "Expense": "Expense",
    "Category": "Category",
    "Category-": "Category :",
    "Category_": "Category<label style='color: red;'>&nbsp;*</label>",
    "Sub Category-": "Sub Category :",
    "Sub Category": "Sub Category",
    "Type_": "Type<label style='color: red;'>&nbsp;*</label>",
    "Type-": "Type :",
    "Type": "Type",
    "All": "All",
    "Preview": "Preview",
    "Preview_": "<i class='fas fa-search mr-1;'></i> Preview",
    "missing 'FormName' field": "Please enter 'Form Name'.",
    "missing 'CompanyName' field": "Please enter 'Company Name'.",
    "missing 'Company Name' field": "Please select 'Company Name'.",
    "missing 'Company Name(Key)' field": "Please select 'Company Name(Key)'.",
    "Add create form success.": "Add create form success.",
    "Edit master form success.": "Edit master form success.",
    "Success": "Success",
    "Last Month": "Last Month",
    "This Month": "This Month",
    "Prefix-": "Prefix :",
    "Prefix": "Prefix",
    "Prefix List": "Prefix List",
    "Add Prefix": "Add Prefix",
    "Edit Prefix": "Edit Prefix",
    "Prefix Name": "Prefix Name",
    "Web Name": "Web Name",
    "Prefix Name_": "Prefix Name<label style='color: red;'>&nbsp;*</label>",
    "Web Name_": "Web Name<label style='color: red;'>&nbsp;*</label>",
    "missing 'Prefix' field": "Please select 'Prefix'.",
    "missing 'Web Name' field": "Please enter 'Web Name'.",
    "Add prefix success.": "Add prefix success.",
    "Edit prefix success.": "Edit prefix success.",
    "Add Transaction_": "<i class='fas fa-plus mr-1;'></i>Add Transaction",
    "Add Transaction": "Add Transaction",
    "Edit Transaction": "Edit Transaction",
    "Edit Master Form": "Edit Master Form",
    "Name": "Name",
    "Name-": "Name :",
    "Name_": "Name<label style='color: red;'>&nbsp;*</label>",
    "AMT": "Amount",
    "Amount": "Amount",
    "Amount-": "Amount :",
    "Amount_": "Amount<label style='color: red;'>&nbsp;*</label>",
    "missing 'Amount' field": "Please enter 'Amount'.",
    "Description": "Description",
    "Description-": "Description :",
    "Description_": "Description<label style='color: red;'>&nbsp;*</label>",
    "Remark": "Remark",
    "Remark-": "Remark :",
    "Account Receive No.": "Account No.",
    "Account Receive No.-": "Account No. :",
    "Account Receive No._": "Account No.<label style='color: red;'>&nbsp;*</label>",
    "missing 'Account Receive No.' field": "Please enter 'Account No.'",
    "Account Receive Name": "Account Name",
    "Account Receive Name-": "Account Name :",
    "Account Receive Name_": "Account Name<label style='color: red;'>&nbsp;*</label>",
    "missing 'Account Receive Name' field": "Please enter 'Account Name'.",
    "Bank List": "Bank List",
    "Edit Bank": "Edit Bank",
    "Edit bank success.": "Edit bank success.",
    "Add Bank_": "<i class='fas fa-plus mr-1;'></i>Add Bank",
    "Add Bank": "Add Bank",
    "Add bank success.": "Add bank success.",
    "Delete Bank": "Delete Bank",
    "Delete bank success.": "Delete bank success.",
    "Bank": "Bank",
    "Bank-": "Bank :",
    "Bank_": "Bank<label style='color: red;'>&nbsp;*</label>",
    "missing 'Bank' field": "Please select 'Bank'.",
    "Company ID": "Company ID",
    "missing 'Category' field": "Please select 'Category'.",
    "missing 'Type' field": "Please select 'Type'.",
    "missing 'MasterForm' field": "Please select 'Master Form'.",
    "Add transaction success.": "Add transaction success.",
    "Save transaction success.": "Save transaction success.",
    "Rent Amount": "Rent Amount",
    "Rent Amount-": "Rent Amount :",
    "Win/Lose Amount": "Win/Lose Amount",
    "Win/Lose Amount-": "Win/Lose Amount :",
    "ApiKey": "API Key",
    "ApiKey-": "API Key :",
    "Hosting/Bot Server Amount": "Hosting/Bot Server Amount",
    "Hosting/Bot Server Amount-": "Hosting/Bot Server Amount :",
    "TrueWallet Amount": "TrueWallet Amount",
    "TrueWallet Amount-": "TrueWallet Amount :",
    "Affiliate Amount": "Affiliate Amount",
    "Affiliate Amount-": "Affiliate Amount :",
    "Percent": "Percent",
    "Percent_": "Percent<label style='color: red;'>&nbsp;*</label>",
    "Percent Amount": "Percent Amount (%)",
    "Percent Amount-": "Percent Amount (%) :",
    "missing 'Percent' field": "Please enter 'Percent'.",
    "Owner": "Owner",
    "Owner-": "Owner :",
    "Date": "Date",
    "Previous Form": "Previous Form",
    "Edit": "Edit",
    "View": "View",
    "View/Edit": "View/Edit",
    "View history / Edit": "View history / Edit",
    "View history/View/Edit": "View history/View/Edit",
    "View history/View": "View history/View",
    "Image Slip": "Image Slip",
    "Image Slip Detail": "Image Slip Detail",
    "Attach File": "Attach File",
    "Management": "Management",
    "Generate Report": "Generate Report",
    "Unconfirmed+": " <i class='fas fa-times-x mr-1;'></i> Unconfirmed",
    "Confirm+": " <i class='fas fa-check mr-1;'></i> Confirm",
    "Unconfirmed": "Unconfirmed",
    "Unconfirmed Bill": "Unconfirmed Bill",
    "Confirm": "Confirm",
    "Confirm 1": "Confirm 1",
    "Confirm 2": "Confirm 2",
    "Confirm 3": "Confirm 3",
    "Complete": "Complete",
    "Done": "Done",
    "If status": "If the status is 'Complete' then this can be done.",
    "Add Member_": "<i class='fas fa-plus mr-1;'></i>Add Member",
    "Add Member": "Add Member",
    "Add User Role_": "<i class='fas fa-plus mr-1;'></i>Add User Role",
    "Add User Role": "Add User Role",
    "Add Account_": "<i class='fas fa-plus mr-1;'></i>Add Account",
    "Add Account": "Add Account",
    "Edit Account": "Edit Account",
    "Add account success.": "Add account success.",
    "Edit account success.": "Edit account success.",
    "Edit User Role": "Edit User Role",
    "Add user role success.": "Add user role success.",
    "Edit user role success.": "Edit user role success.",
    "Detail": "Detail",
    "detail+": "detail...",
    "Information": "Information",
    "Total Tran ApiKey": "Total Tran. Api Key",
    "Total Tran Amount": "Total Tran. Amount",
    "Total Tran Amount-": "Total Tran. Amount:",
    "Total Tran Slip": "Total Tran. Slip",
    "Total Tran Slip-": "Total Tran. Slip :",
    "Difference": "Difference",
    "Difference_": "<i class='fas fa-arrows-alt-v'></i> Difference",
    "System User Role": "System User Role",
    "System Account": "System Account",
    "System Setting": "System Setting",
    "Phone number": "Phone number",
    "missing 'Role' field": "Please select 'Role'.",
    "Edit Status": "Edit Status",
    "Edit status success.": "Edit status success.",
    "Change Password": "Change Password",
    "Old Password": "Old Password<label style='color: red;'>&nbsp;*</label>",
    "New Password": "New Password<label style='color: red;'>&nbsp;*</label>",
    "Confirm Password": "Confirm Password<label style='color: red;'>&nbsp;*</label>",
    "Incorrect Old Password": "Incorrect Old Password",
    "missing 'Old Password' field": "Please enter 'Old Password'.",
    "missing 'New Password' field": "Please enter 'New Password'.",
    "missing 'Confirm Password' field": "Please enter 'Confirm Password'.",
    "New password doesn't match confirm password": "New password doesn't match confirm password",
    "Change new password success": "Change new password success",
    "Confirm edit status this item ?": "Confirm edit status this item ?",
    "missing 'Name' field": "Please enter 'Name'.",
    "Menu Master Form": "Master Form",
    "Master Form Category": "Master Form Category",
    "Master Form Sub Category": "Master Form Sub Category",
    "Add Category_": "<i class='fas fa-plus mr-1;'></i>Add Category",
    "Add Sub Category_": "<i class='fas fa-plus mr-1;'></i>Add Sub Category",
    "Add Master Form Category": "Add Master Form Category",
    "Edit Master Form Category": "Edit Master Form Category",
    "Add Master Form Sub Category": "Add Master Form Sub Category",
    "Edit Master Form Sub Category": "Edit Master Form Sub Category",
    "Current form main category": "Current form main category",
    "Add master form category success.": "Add master form category success.",
    "Edit master form category success.": "Edit master form category success.",
    "Add master form sub category success.": "Add master form sub category success.",
    "Edit master form sub category success.": "Edit master form sub category success.",
    "Add Capital_": "<i class='fas fa-plus mr-1;'></i>Add Capital",
    "Add Shareholder_": "<i class='fas fa-plus mr-1;'></i>Add Shareholder",
    "Capital Amount": "Capital Amount",
    "Used Amount": "Used Amount",
    "Remaining Amount": "Remaining Amount",
    "Edit Capital Amount": "Edit Capital Amount",
    "Add Capital Amount": "Add Capital Amount",
    "Edit capital amount success.": "Edit capital amount success.",
    "Add capital amount success.": "Add capital amount success.",
    "Transaction Category": "Transaction Category",
    "Add Transaction Category_": "<i class='fas fa-plus mr-1;'></i>Add Transaction Category",
    "Add Transaction Category": "Add Transaction Category",
    "Edit Transaction Category": "Edit Transaction Category",
    "Add transaction category success.": "Add transaction category success.",
    "Edit transaction category success.": "Edit transaction category success.",
    "Duplicate": "Duplicate",
    "Duplicate": "Duplicate",
    "View History": "View History",
    "Description History": "Description History",
    "Currency History": "Currency History",
    "Create date": "Create date",
    "Create by": "Create by",
    "Create role": "Create role",
    "Modify date": "Modify date",
    "Update by": "Update by",
    "Update role": "Update role",
    "No data.": "No data.",
    "No": "No",
    "Yes": "Yes",
    "Duplicate master form this item ?": "Duplicate master form this item ?",
    "Duplicate transaction in master form this item ?": "Duplicate transaction in master form this item ?",
    "Duplicate master form success.": "Duplicate master form success.",
    "Duplicate master form and transaction success.": "Duplicate master form and transaction success.",
    "Company Type": "Company Type",
    "Company Type-": "Company Type :",
    "Company Type_": "Company Type<label style='color: red;'>&nbsp;*</label>",
    "Sub-Company Type": "Sub-Company Type",
    "Sub-Company Type-": "Sub-Company Type :",
    "Sub-Company Type_": "Sub-Company Type<label style='color: red;'>&nbsp;*</label>",
    "missing 'Sub-Company Type' field": "Please select 'Sub-Company Type'.",
    "missing 'Company Type' field": "Please select 'Company Type'.",
    "Total Revenue": "Total Revenue",
    "Total Expense": "Total Expense",
    "Total Revenue-": "Total Revenue :",
    "Total Expense-": "Total Expense :",
    "Confirm this item ?": "Confirm this item ?",
    "Confirm success.": "Confirm success.",
    "Confirm fail": "Confirm fail. This user has verified.",
    "Quantity-": "Quantity :",
    "Quantity": "Quantity",
    "Quantity_": "Quantity<label style='color: red;'>&nbsp;*</label>",
    "missing 'Quantity' field": "Please enter 'Quantity'.",
    "Unit": "Unit",
    "Unit-": "Unit :",
    "Unit_": "Unit<label style='color: red;'>&nbsp;*</label>",
    "Export Excel": "Export Excel",
    "Outstanding": "Outstanding",
    "Paid-Outstanding": "Paid-Outstanding",
    "Amount/Baht": "Amount/Baht",
    "0001": "Last month balance :",
    "0002": "Profit this month (กำไร-รายรับ เดือนนี้) :",
    "0012": "Profit this month (กำไร-รายรับ เดือนนี้)[USDT] :",
    "0003": "Outstading Balance :",
    "0013": "Outstading Balance[USDT] :",
    "0004": "Total this month (รวมค่าใช้จ่ายทั้งหมด เดือนนี้) :",
    "0014": "Total this month (รวมค่าใช้จ่ายทั้งหมด เดือนนี้)[USDT] :",
    "0005": "Net Profit :",
    "0006": "Share Holder :",
    "0007": "P'Win 2.5% :",
    "0008": "Share P'Pentor 50% [โอนเงินเข้าเก็บบัญชี PTG] :",
    "0009": "Current Balance (this month) :",
    "0010": "Share Holder 47.5% [ Snocko ] :",
    "0011": "Capital amount :",
    "+add image": "+add image",
    "+add amount": "+add amount",
    "+add api key": "+add api key",
    "+add currency": "+add currency",
    "-delete currency": "-delete currency",
    "+add system": "+add system",
    "-remove": "-remove",
    "Total": "Total",
    "Total_": "Total :",
    "Total-": "Total<label style='color: red;'>&nbsp;*</label>",
    "Payment Status": "Payment Status",
    "Payment": "Payment",
    "Payment-": "Payment :",
    "Paid": "Paid",
    "Unpaid": "Unpaid",
    "textnumberonly": "Enter only number (0-9) or letter (A-Z, a-z).",
    "numberonly": "Enter only number (0-9).",
    "textonly": "Enter only letter (A-Z, a-z, ก-ฮ).",
    "textTHnumberonly": "Enter only number (0-9) or letter (A-Z, a-z, ก-ฮ).",
    "passwordonly": "Password must longer than 6 characters.",
    "Duplicate Username": "Duplicate Username",
    "Duplicate User Role": "Duplicate User Role",
    "Duplicate Capital Amount": "Duplicate Capital Amount",
    "Duplicate Company Name": "Duplicate Company Name",
    "Duplicate Company Name(Key)": "Duplicate Company Name(Key)",
    "Duplicate Account No.": "Duplicate Account No.",
    "Duplicate Bill No.": "Duplicate Bill No.",
    "Duplicate Currency(Short Name)": "Duplicate Currency(Short Name)",
    "User Role_": "User Role<label style='color: red;'>&nbsp;*</label>",
    "missing 'User Role' field": "Please enter 'User Role'.",
    "Previous": "Previous",
    "Yesterday": "Yesterday",
    "This week": "This week",
    "Last week": "Last week",
    "This month": "This month",
    "Last month": "Last month",
    "Next": "Next",
    "Today": "Today",
    "Last Week": "Last Week",
    "Last Month": "Last Month",
    "Add System Setting_": "<i class='fas fa-plus mr-1;'></i>Add System Setting",
    "Add System Setting": "Add System Setting",
    "Edit System Setting": "Edit System Setting",
    "%": "%",
    "Add system setting success.": "Add system setting success.",
    "Save system setting success.": "Save system setting success.",
    "missing 'image file' field": "Upload only image files.",
    "Month-": "Month :",
    "Month": "Month",
    "January": "January",
    "February": "February",
    "March": "March",
    "April": "April",
    "May": "May",
    "June": "June",
    "July": "July",
    "August": "August",
    "September": "September",
    "October": "October",
    "November": "November",
    "December": "December",
    "Year-": "Year :",
    "Year": "Year",
    "Company Management": "Company Management",
    "Bank Management": "Bank Management",
    "Currency Management": "Currency Management",
    "Company User Management": "Company User Management",
    "Add Company_": "<i class='fas fa-plus mr-1;'></i>Add Company",
    "Add Company": "Add Company",
    "Edit Company": "Edit Company",
    "Inhouse": "Inhouse",
    "Outhouse": "Outhouse",
    "Add company success.": "Add company success.",
    "Edit company success.": "Edit company success.",
    "Savings Account": "Savings Account",
    "Crypto Currency": "Crypto Currency",
    "Fixed Deposit Account": "Fixed Deposit Account",
    "Current Account": "Current Account",
    "continue>": "continue <i class='fas fa-arrow-right mr-1;'></i>",
    "Multiple Slip?": "Multiple Slip?",
    "missing 'continue>' field": "Please 'continue <i class='fas fa-arrow-right mr-1;'></i>'",
    "missing 'Total' field": "No data 'Total'.",
    "missing 'SlipAmt' field": "Please enter 'Amount' Slip.",
    "missing 'Same' field": "'Total' and 'Amount' slip are not the same.",
    "Transaction Amount": "Transaction Amount",
    "Generate/Edit Bill": "Generate/Edit Bill",
    "Add generate bill success.": "Add generate bill success.",
    "Edit generate bill success.": "Edit bill success.",
    "Generate Bill": "Generate Bill",
    "Edit Bill": "Edit Bill",
    "Edit Bill_": "<i class='fas fa-pencil-alt mr-1;'></i> Edit Bill",
    "Generate Bill_": "<i class='fas fa-plus mr-1;'></i> Generate Bill",
    "Add Description": "Add Description",
    "Edit Description": "Edit Description",
    "Delete Description": "Delete Description",
    "Delete Description Success.": "Delete description success.",
    "Add Description>": "<i class='fas fa-plus-white mr-1;'></i> Add Description",
    "Unit/Price": "Unit/Price",
    "Unit/Price_": "Unit/Price<label style='color: red;'>&nbsp;*</label>",
    "missing 'Unit/Price' field": "Please enter 'Unit/Price'.",
    "Action": "Action",
    "Confirm delete this item ?": "Confirm delete this item ?",
    "Delete": "Delete",
    "BAHT": "Baht",
    "Net Amount": "Net Amount",
    "Net Amount_": "Net Amount :",
    "Total Price._": "Total Price. :",
    "Discount": "Discount",
    "Discount cash": "Discount cash",
    "Discount cash_": "Discount cash :",
    "Discount cash-": "Discount cash<label style='color: red;'>&nbsp;*</label>",
    "Total after Dis._": "Total after Dis. :",
    "VAT": "VAT",
    "VAT 7%_": "VAT 7% :",
    "VAT-": "VAT<label style='color: red;'>&nbsp;*</label>",
    "Total Payment": "Total Payment",
    "Total Payment._": "Total Payment. :",
    "Total Payment(USDT)._": "Total Payment.(USDT) :",
    "missing 'Discount cash' field": "Please enter 'Discount cash'.",
    "missing 'Discount' field": "Please enter 'Discount'.",
    "missing 'VAT' field": "Please enter 'VAT'.",
    "Confirm_": "<i class='fas fa-check mr-1;'></i> Confirm",
    "Monthly Fee_": "Monthly Fee<label style='color: red;'>&nbsp;*</label>",
    "Bill No._": "Bill No. <label style='color: red;'>&nbsp;*</label>",
    "Bill No.-": "Bill No. :",
    "Bill No.": "Bill No.",
    "File Name_": "File Name <label style='color: red;'>&nbsp;*</label>",
    "File Name": "File Name",
    "missing 'Monthly Fee' field": "Please enter 'Monthly Fee'.",
    "missing 'Bill No' field": "Please enter 'Bill No.'.",
    "missing 'File Name' field": "Please enter 'File Name'.",
    "Shareholder": "Shareholder",
    "Incorrect Amount, Please try Again.": "Incorrect Amount, Please try Again.",
    "Incorrect Date, Please try Again.": "Incorrect Date, Please try Again.",
    "Add shareholder amount success.": "Add shareholder amount success.",
    "Edit shareholder amount success.": "Edit shareholder amount success.",
    "Add Shareholder Amount": "Add Shareholder Amount",
    "Edit Shareholder Amount": "Edit Shareholder Amount",
    "(Key)": "(Key)",
    "url": "url",
    "Item Name_": "Item Name<label style='color: red;'>&nbsp;*</label>",
    "missing 'Item Name' field": "Please enter 'Item Name'.",
    "File name for download": "File name for download",
    "Download": "Download",
    "This month's information is available.": "This month's information is available.",
    "This month's data have been confirmed.": "This month's data have been confirmed.",
    "This month's report data have been confirmed.": "This month's report data have been confirmed.",
    "Overdue Balance": "Overdue Balance",
    "Overpayment": "Overpayment",
    "Overpayment/Overdue Balance": "Overpayment/Overdue Balance",
    "Overdue Balance_": "Overdue Balance",
    "Overdue Balance-": "Overdue Balance :",
    "Overpayment_": "Overpayment",
    "Overpayment-": "Overpayment :",
    "Overpayment/Overdue Balance_": "Overpayment/Overdue Balance",
    "Overpay-Outstanding": "Overpay-Outstanding",
    "Transfer Amount": "Transfer Amount",
    "Must be value greater than 0": "Must be value greater than 0",
    "Account Type": "Account Type",
    "Account Type_": "Account Type<label style='color: red;'>&nbsp;*</label>",
    "missing 'Account Type' field": "Please select 'Account Type'.",
    "This Report has no data 'Capital Amount'": "This Report has no data 'Capital Amount'",
    "This Report has no data 'Shareholder'": "This Report has no data 'Shareholder'",
    "This Report has no data 'Bill'": "This Report has no data 'Bill'",
    "Cannot add or edit!": "Cannot 'Add' or 'Edit' !",
    "missing 'Rate - Pay Bill' field": "If filling in 'Pay Bill' , Please enter 'Rate'.",
    "missing 'Rate' field": "Please enter 'Rate'.",
    "missing 'Pay Bill' field": "Please enter 'Pay Bill'.",
    "Incorrect Pay Bill, Please try Again.": "Incorrect 'Pay Bill', Please try Again.",
    "Pay Bill": "Pay Bill",
    "Pay Bill-": "Pay Bill :",
    "Save pay bill success": "Save pay bill success.",
    "Balance Paid": "Balance Paid",
    "Balance Paid_": "Balance Paid :",
    "Company List": "Company List",
    "View more": "View more",
    "Company Prefix": "Company Prefix",
    "Company Prefix-": "Company Prefix :",
    "Company Prefix_": "Company Prefix <label style='color: red;'>&nbsp;*</label>",
    "List": "List",
    "Add List": "Add List",
    "Edit List": "Edit List",
    "Add List>": "<i class='fas fa-plus-white mr-1;'></i> Add List",
    "Delete List": "Delete List",
    "USDT Rate": "USDT Rate",
    "USDT Rate_": "USDT Rate <label style='color: red;'>&nbsp;*</label>",
    "missing 'USDT Rate' field": "Please enter 'USDT Rate'.",
    "(USDT)": "(USDT)",
    "USDT": "USDT",
    "ยอดแปรผัน": "ยอดแปรผัน",
    "ยอดแปรผัน USDT": "ยอดแปรผัน USDT",
    "Currency": "Currency",
    "Currency-": "Currency :",
    "(Short Name)": "(Short Name)",
    "Edit Currency": "Edit Currency",
    "Delete Currency": "Delete Currency",
    "Add Currency_": "<i class='fas fa-plus mr-1;'></i>Add Currency",
    "Add Currency": "Add Currency",
    "Currency_": "Currency<label style='color: red;'>&nbsp;*</label>",
    "Currency(Short Name)_": "Currency(Short Name)<label style='color: red;'>&nbsp;*</label>",
    "missing 'Currency' field": "Please enter 'Currency'",
    "missing 'Currency(Short Name)' field": "Please enter 'Currency(Short Name)'.",
    "missing 'Currency(Short Name)-' field": "Please select 'Currency(Short Name)'.",
    "Add currency success.": "Add currency success.",
    "Edit currency success.": "Edit currency success.",
    "Delete currency success.": "Delete currency success.",
    "Rate": "Rate",
    "Rate-": "Rate :",
    "Fee_": "Fee :",
    "Fee": "Fee",
    "missing 'Fee' field": "Please enter 'Fee'.",
    "Cannot Delete": "This item has been paid and cannot be deleted.<br/> Please contact admin.",



    "Data recording failed.": "Data recording failed. Please try again.",
};

var Thai = {
    "Ask Me Bet": "Ask Me Bet",
    "Askmebet": "Askmebet",
    "Chat Bot": "Chat Bot",
    "Search User": "Search User",
    "Pretty Gaming": "Pretty Gaming",
    "Super Slot": "Super Slot",
    "Football": "Football",
    "Lotto": "Lotto",
    "Ambbet": "Ambbet",
    "missing 'Contact' field": "Please enter 'Contact'.",
    "missing 'Level' field": "Please select 'Level'.",
    "Add new member success.": "Add new member success.",
    "Username is duplicate.": "Username is duplicate.",
    "Delete Member": "Delete Member",
    "Delete member success.": "Delete member success.",
    "Edit member success.": "Edit member success.",
    "Login failed.": "Login failed. Please try again.",
    "Please select type.": "Please select type.",
    "Please select agent.": "Please select agent.",
    "Please enter bet ID.": "Please enter bet ID.",
    "Cancel bet ID success.": "Cancel bet ID success.",
    "Add new dashboard success.": "Add new dashboard success.",
    "missing 'Product' field": "Please enter your 'Product'.",
    "missing 'Agent' field": "Please enter your 'Agent'.",
    "missing 'Attach file' field": "Please select 'Attach file'.",
    "missing 'Start date' field": "Please enter your 'Start date'.",
    "missing 'To date' field": "Please enter your 'To date'.",
    "missing 'Description' field": "กรุณากรอก 'คำอธิบาย'.",
    "Add new leave success.": "Add new leave success.",
    "Approve this leave success.": "Approve this leave success.",
    "Reject this leave success.": "Reject this leave success.",
    //
    "OK": "ยืนยัน",
    "Save": "บันทึก",
    "Mobile Version": "<i class='fas fa-mobile'></i>&nbsp;เวอร์ชั่นมือถือ",
    "Incorrect Username or Password, Please try Again.": "ชื่อผู้ใช้หรือรหัสผ่านไม่ถูกต้อง",
    "Incorrect Username": "บัญชีไม่ได้ใช้งาน กรุณาติดต่อผู้ดูแล.",
    "Contact your associate in case you forgot the password or unable to sign in": "ติดต่อตัวแทนของคุณในกรณีที่คุณลืมรหัสผ่านหรือไม่สามารถลงชื่อเข้าใช้ได้",
    "Username": "ชื่อผู้ใช้",
    "Username_": "ชื่อผู้ใช้<label style='color: red;'>&nbsp;*</label>",
    "Password": "รหัสผ่าน",
    "Password_": "รหัสผ่าน<label style='color: red;'>&nbsp;*</label>",
    "Sign in": "เข้าสู่ระบบ",
    "Log Out": "<i class='fas fa-sign-out-alt'></i>&nbsp;ออกจากระบบ",
    "Close": "ปิด",
    "Guide": "<i class='fas fa-guide'></i>&nbsp;คู่มือการใช้งาน",
    "Dashboard": "รายละเอียดของคุณ",
    "Quotation List": "รายการใบเสนอราคา",
    "Quotation No": "เลขที่ใบเสนอราคา",
    "Upload Silp": "อัพโหลดสลิป",
    "PDF File": "ไฟล์พีดีเอฟ",
    "Slip": "สลิป",
    "Upload": "อัพโหลด",
    "Member": "สมาชิก",
    "Member List": "รายการสมาชิก",
    "Please enter search.": "กรุณากรอกค้นหา.",
    "Search": "ค้นหา",
    "Search-": "ค้นหา :",
    "First name/Last name": "ชื่อ / นามสกุล",
    "Select": "เลือก",
    "All": "ทั้งหมด",
    "No.": "ลำดับ",
    "First Name": "ชื่อ",
    "Last Name": "นามสกุล",
    "Nickname": "ชื่อเล่น",
    "Role": "Role",
    "Role_": "Role<label style='color: red;'>&nbsp;*</label>",
    "Status": "สถานะ",
    "Status-": "สถานะ :",
    "Status_": "สถานะ<label style='color: red;'>&nbsp;*</label>",
    "missing 'Status' field": "กรุณาเลือก 'สถานะ'.",
    "Last login date": "วันที่ล็อคอินล่าสุด",
    "Active": "ใช้งาน",
    "Inactive": "ไม่ใช้งาน",
    "Report": "รายงาน",
    "Master Form": "แบบฟอร์มหลัก",
    "Master Form-": "แบบฟอร์มหลัก :",
    "Master Form_": "แบบฟอร์มหลัก<label style='color: red;'>&nbsp;*</label>",
    "Create Form": "สร้างแบบฟอร์ม",
    "Dashboard Report": "รายงานรายละเอียดของคุณ",
    "Add Master Form_": "<i class='fas fa-plus mr-1;'></i>สร้างแบบฟอร์มใหม่",
    "Add Master Form": "สร้างแบบฟอร์มใหม่",
    "to": "ถึง",
    "Start date-": "วันที่เริ่มต้น :",
    "To date-": "ถึงวันที่ :",
    "Start date": "วันที่เริ่มต้น",
    "End date": "วันที่สิ้นสุด",
    "To date": "ถึงวันที่",
    "missing 'Start-To Date' field": "'ถึงวันที่' ต้องมีค่ามากกว่า 'วันที่เริ่มต้น'.",
    "Basic Info": "ข้อมูลพื้นฐาน",
    "Form Name_": "ชื่อแบบฟอร์ม<label style='color: red;'>&nbsp;*</label>",
    "Form Name": "ชื่อแบบฟอร์ม",
    "Company Name_": "ชื่อบริษัท<label style='color: red;'>&nbsp;*</label>",
    "Company Name": "ชื่อบริษัท",
    "Company Name-": "ชื่อบริษัท :",
    "Create": "สร้าง",
    "Discard": "ยกเลิก",
    "Transaction": "ธุรกรรม",
    "Add/Edit Transaction": "เพิ่ม/แก้ไข ธุรกรรม",
    "Add/Edit Master Form": "เพิ่ม/แก้ไข แบบฟอร์มหลัก",
    "My task": "งานของฉัน",
    "Revenue": "รายรับ",
    "Expense": "รายจ่าย",
    "Category": "ประเภท",
    "Category-": "ประเภท :",
    "Category_": "ประเภท<label style='color: red;'>&nbsp;*</label>",
    "Sub Category-": "ประเภทย่อย :",
    "Sub Category": "ประเภทย่อย",
    "Type_": "ประเภท<label style='color: red;'>&nbsp;*</label>",
    "Type-": "ประเภท :",
    "Type": "ประเภท",
    "All": "ทั้งหมด",
    "Preview": "ดูตัวอย่าง",
    "Preview_": "<i class='fas fa-search mr-1;'></i> ดูตัวอย่าง",
    "missing 'FormName' field": "กรุณากรอก 'ชื่อแบบฟอร์ม'.",
    "missing 'CompanyName' field": "กรุณากรอก 'ชื่อบริษัท'.",
    "missing 'Company Name' field": "กรุณาเลือก 'ชื่อบริษัท'.",
    "missing 'Company Name(Key)' field": "กรุณาเลือก 'ชื่อบริษัท(Key)'.",
    "missing 'Category' field": "กรุณาเลือก 'ประเภท'.",
    "missing 'Username' field": "กรุณากรอก 'ชื่อผู้ใช้'.",
    "missing 'Password' field": "กรุณากรอก 'รหัสผ่าน'.",
    "missing 'Type' field": "กรุณาเลือก 'ประเภท'.",
    "missing 'MasterForm' field": "กรุณาเลือก 'แบบฟอร์มหลัก'.",
    "Add create form success.": "เพิ่มสร้างแบบฟอร์มสำเร็จ.",
    "Edit master form success.": "แก้ไขสร้างแบบฟอร์มสำเร็จ.",
    "Success": "สำเร็จ",
    "Last Month": "เดือนที่แล้ว",
    "Prefix-": "Prefix :",
    "Prefix": "Prefix",
    "Prefix List": "Prefix List",
    "Add Prefix": "Add Prefix",
    "Edit Prefix": "Edit Prefix",
    "Prefix Name": "Prefix Name",
    "Web Name": "Web Name",
    "Prefix Name_": "Prefix Name<label style='color: red;'>&nbsp;*</label>",
    "Web Name_": "Web Name<label style='color: red;'>&nbsp;*</label>",
    "missing 'Prefix' field": "กรุณาเลือก 'Prefix'.",
    "missing 'Web Name' field": "กรุณากรอก 'Web Name'.",
    "Add prefix success.": "เพิ่ม Prefix สำเร็จ.",
    "Edit prefix success.": "แก้ไข Prefix สำเร็จ.",
    "Add Transaction_": "<i class='fas fa-plus mr-1;'></i>เพิ่มธุรกรรมใหม่",
    "Add Transaction": "เพิ่มธุรกรรมใหม่",
    "Edit Transaction": "แก้ไขธุรกรรม",
    "Edit Master Form": "แก้ไขแบบฟอร์มหลัก",
    "Name": "ชื่อ",
    "Name-": "ชื่อ :",
    "Name_": "ชื่อ<label style='color: red;'>&nbsp;*</label>",
    "AMT": "จำนวน",
    "Amount": "จำนวนเงิน",
    "Amount-": "จำนวนเงิน :",
    "Amount_": "จำนวนเงิน<label style='color: red;'>&nbsp;*</label>",
    "missing 'Amount' field": "กรุณากรอก 'จำนวนเงิน'.",
    "Description": "คำอธิบาย",
    "Description-": "คำอธิบาย :",
    "Description_": "คำอธิบาย<label style='color: red;'>&nbsp;*</label>",
    "Remark": "หมายเหตุ",
    "Remark-": "หมายเหตุ :",
    "Account Receive No.": "เลขที่บัญชี",
    "Account Receive No.-": "เลขที่บัญชี :",
    "Account Receive No._": "เลขที่บัญชี<label style='color: red;'>&nbsp;*</label>",
    "missing 'Account Receive No.' field": "กรุณากรอก 'เลขที่บัญชี'.",
    "Account Receive Name": "ชื่อบัญชี",
    "Account Receive Name-": "ชื่อบัญชี :",
    "Account Receive Name_": "ชื่อบัญชี<label style='color: red;'>&nbsp;*</label>",
    "missing 'Account Receive Name' field": "กรุณากรอก 'ชื่อบัญชี'.",
    "Bank List": "รายชื่อธนาคาร",
    "Edit Bank": "แก้ไขธนาคาร",
    "Add Bank_": "<i class='fas fa-plus mr-1;'></i>เพิ่มธนาคาร",
    "Add Bank": "เพิ่มธนาคาร",
    "Delete Bank": "ลบธนาคาร",
    "Add bank success.": "เพิ่มธนาคารสำเร็จ.",
    "Edit bank success.": "แก้ไขธนาคารสำเร็จ.",
    "Delete bank success.": "ลบธนาคารสำเร็จ.",
    "Bank": "ธนาคาร",
    "Bank-": "ธนาคาร :",
    "Bank_": "ธนาคาร<label style='color: red;'>&nbsp;*</label>",
    "missing 'Bank' field": "กรุณาเลือก 'ธนาคาร'.",
    "Company ID": "รหัสบริษัท",
    "Add transaction success.": "เพิ่มธุรกรรมใหม่สำเร็จ.",
    "Save transaction success.": "บันทึกธุรกรรมใหม่สำเร็จ.",
    "Rent Amount": "จำนวนค่าเช่า",
    "Rent Amount-": "จำนวนค่าเช่า :",
    "Win/Lose Amount": "จำนวนค่าแพ้/ชนะ",
    "Win/Lose Amount-": "จำนวนค่าแพ้/ชนะ :",
    "ApiKey": "API Key",
    "ApiKey-": "API Key :",
    "Hosting/Bot Server Amount": "จำนวนค่าHosting/Bot Server",
    "Hosting/Bot Server Amount-": "จำนวนค่าHosting/Bot Server :",
    "TrueWallet Amount": "จำนวนค่าTrueWallet",
    "TrueWallet Amount-": "จำนวนค่าTrueWallet :",
    "Affiliate Amount": "จำนวนค่าAffiliate",
    "Affiliate Amount-": "จำนวนค่าAffiliate :",
    "Percent": "เปอร์เซ็นต์",
    "Percent_": "เปอร์เซ็นต์<label style='color: red;'>&nbsp;*</label>",
    "Percent Amount": "จำนวนค่าเปอร์เซ็นต์ (%)",
    "Percent Amount-": "จำนวนค่าเปอร์เซ็นต์ (%) :",
    "missing 'Percent' field": "กรุณากรอก 'เปอร์เซ็นต์'.",
    "Owner": "เจ้าของ",
    "Owner-": "เจ้าของ :",
    "Date": "วันที่",
    "Previous Form": "แบบฟอร์มก่อนหน้า",
    "Edit": "แก้ไข",
    "View": "ดู",
    "View/Edit": "ดู/แก้ไข",
    "View history / Edit": "ดูประวัติ / แก้ไข",
    "View history/View/Edit": "ดูประวัติ/ดู/แก้ไข",
    "View history/View": "ดูประวัติ/ดู",
    "Image Slip": "รูปภาพสลิป",
    "Image Slip Detail": "รายละเอียดรูปภาพสลิป",
    "Attach File": "แนบไฟล์",
    "Management": "การจัดการ",
    "Generate Report": "สร้างรายงาน",
    "Unconfirmed+": " <i class='fas fa-times-x mr-1;'></i> ยังไม่ยืนยัน",
    "Confirm+": " <i class='fas fa-check mr-1;'></i> ยืนยัน",
    "Unconfirmed": "ยังไม่ยืนยัน",
    "Unconfirmed Bill": "บิลที่ยังไม่ยืนยัน",
    "Confirm": "ยืนยัน",
    "Confirm 1": "ยืนยัน 1",
    "Confirm 2": "ยืนยัน 2",
    "Confirm 3": "ยืนยัน 3",
    "Complete": "ครบถ้วน",
    "Done": "เสร็จสิ้น",
    "If status": "หากสถานะเป็น 'ครบถ้วน' จึงจะสามารถดำเนินการได้",
    "Add Member_": "<i class='fas fa-plus mr-1;'></i>เพิ่มสมาชิก",
    "Add Member": "เพิ่มสมาชิก",
    "Add User Role_": "<i class='fas fa-plus mr-1;'></i>เพิ่มผู้ใช้ระบบ",
    "Add User Role": "เพิ่มผู้ใช้ระบบ",
    "Edit User Role": "แก้ไขผู้ใช้ระบบ",
    "Add Account_": "<i class='fas fa-plus mr-1;'></i>เพิ่มผู้ใช้",
    "Add Account": "เพิ่มผู้ใช้",
    "Edit Account": "แก้ไขผู้ใช้",
    "Add account success.": "เพิ่มผู้ใช้สำเร็จ.",
    "Edit account success.": "แก้ไขผู้ใช้สำเร็จ.",
    "Detail": "รายละเอียด",
    "detail+": "รายละเอียด...",
    "Information": "ข้อมูล",
    "Total Tran ApiKey": "จำนวนเงิน Api Key ทั้งหมด",
    "Total Tran Amount": "จำนวนเงินธุรกรรมทั้งหมด",
    "Total Tran Amount-": "จำนวนเงินธุรกรรมทั้งหมด:",
    "Total Tran Slip": "จำนวนเงินสลิปธุรกรรมทั้งหมด",
    "Total Tran Slip-": "จำนวนเงินสลิปธุรกรรมทั้งหมด:",
    "Difference": "ผลต่าง",
    "Difference_": "<i class='fas fa-arrows-alt-v'></i> ผลต่าง",
    "System User Role": "บทบาทผู้ใช้ระบบ",
    "System Account": "ระบบผู้ใช้",
    "System Setting": "การตั้งค่าระบบ",
    "Phone number": "เบอร์โทรศัพท์",
    "missing 'Role' field": "กรุณาเลือก. 'Role'.",
    "Add user role success.": "เพิ่มผู้ใช้ระบบสำเร็จ.",
    "Edit user role success.": "เเก้ไขผู้ใช้ระบบสำเร็จ.",
    "Edit Status": "แก้ไขสถานะ",
    "Edit status success.": "เเก้ไขสถานะสำเร็จ.",
    "Change Password": "เปลี่ยนรหัสผ่าน",
    "Old Password": "รหัสผ่านเดิม<label style='color: red;'>&nbsp;*</label>",
    "New Password": "รหัสผ่านใหม่<label style='color: red;'>&nbsp;*</label>",
    "Confirm Password": "ยืนยันรหัสผ่านใหม่<label style='color: red;'>&nbsp;*</label>",
    "Incorrect Old Password": "รหัสผ่านเดิมไม่ถูกต้อง",
    "missing 'Old Password' field": "กรุณากรอก 'รหัสผ่านเดิม'.",
    "missing 'New Password' field": "กรุณากรอก 'รหัสผ่านใหม่'.",
    "missing 'Confirm Password' field": "กรุณากรอก 'ยืนยันรหัสผ่าน'.",
    "New password doesn't match confirm password": "รหัสผ่านใหม่ไม่ตรงกับรหัสผ่านยืนยัน",
    "Change new password success": "เปลี่ยนรหัสผ่านใหม่สำเร็จ",
    "Confirm edit status this item ?": "ยืนยันการแก้ไขสถานะรายการนี้ ?",
    "missing 'Name' field": "กรุณากรอก 'ชื่อ'.",
    "Menu Master Form": "แบบฟอร์ม",
    "Master Form Category": "ประเภทฟอร์มหลัก",
    "Master Form Sub Category": "ประเภทฟอร์มย่อย",
    "Add Category_": "<i class='fas fa-plus mr-1;'></i>เพิ่มฟอร์มหลัก",
    "Add Sub Category_": "<i class='fas fa-plus mr-1;'></i>เพิ่มฟอร์มย่อย",
    "Add Master Form Category": "เพิ่มประเภทฟอร์มหลัก",
    "Edit Master Form Category": "เเก้ไขประเภทฟอร์มหลัก",
    "Add Master Form Sub Category": "เพิ่มประเภทฟอร์มย่อย",
    "Edit Master Form Sub Category": "เเก้ไขประเภทฟอร์มย่อย",
    "ชื่อ_": "Name<label style='color: red;'>&nbsp;*</label>",
    "Current form main category": "หมวดหมู่ของฟอร์มหลัก",
    "Add master form category success.": "เพิ่มประเภทฟอร์มหลักสำเร็จ.",
    "Edit master form category success.": "แก้ไขประเภทฟอร์มหลักสำเร็จ.",
    "Add master form sub category success.": "เพิ่มประเภทฟอร์มย่อยสำเร็จ.",
    "Edit master form sub category success.": "แก้ไขประเภทฟอร์มย่อยสำเร็จ.",
    "Add Capital_": "<i class='fas fa-plus mr-1;'></i>เพิ่มทุนหมุนเวียน",
    "Add Shareholder_": "<i class='fas fa-plus mr-1;'></i>เพิ่มตัวแทน",
    "Capital Amount": "จำนวนทุนหมุนเวียน",
    "Used Amount": "จำนวนเงินที่ใช้",
    "Remaining Amount": "จำนวนเงินที่เหลือ",
    "Edit Capital Amount": "เเก้ไขจำนวนทุนหมุนเวียน",
    "Add Capital Amount": "เพิ่มจำนวนทุนหมุนเวียน",
    "Edit capital amount success.": "แก้ไขจำนวนทุนหมุนเวียนสำเร็จ.",
    "Add capital amount success.": "เพิ่มจำนวนทุนหมุนเวียนสำเร็จ.",
    "Add capital amount success.": "เพิ่มจำนวนทุนหมุนเวียนสำเร็จ.",
    "Transaction Category": "ประเภทธุรกรรม",
    "Add Transaction Category_": "<i class='fas fa-plus mr-1;'></i>เพิ่มประเภทธุรกรรม",
    "Add Transaction Category": "เพิ่มประเภทธุรกรรม",
    "Edit Transaction Category": "เเก้ไขประเภทธุรกรรม",
    "Add transaction category success.": "เพิ่มประเภทธุรกรรมสำเร็จ.",
    "Edit transaction category success.": "แก้ไขประเภทธุรกรรมสำเร็จ.",
    "Duplicate": "ทำสำเนา",
    "View History": "ดูประวัติ",
    "Description History": "ประวัติคำอธิบาย",
    "Currency History": "ประวัติสกุลเงิน",
    "Create date": "วันที่สร้าง",
    "Create by": "สร้างโดย",
    "Create role": "บทบาทผู้สร้าง",
    "Modify date": "วันที่แก้ไข",
    "Update by": "อัปเดตโดย",
    "Update role": "บทบาทผู้อัปเดต",
    "No data.": "ไม่มีข้อมูล.",
    "No": "ไม่ใช่",
    "Yes": "ใช่",
    "Duplicate master form this item ?": "ทำสำเนาแบบฟอร์มหลักรายการนี้ ?",
    "Duplicate transaction in master form this item ?": "ทำสำเนาประเภทธุรกรรมของแบบฟอร์มหลักรายการนี้ ?",
    "Duplicate master form success.": "ทำสำเนาแบบฟอร์มหลักสำเร็จ.",
    "Duplicate master form and transaction success.": "ทำสำเนาแบบฟอร์มหลักและประเภทธุรกรรมสำเร็จ.",
    "Company Type": "ประเภทบริษัท",
    "Company Type-": "ประเภทบริษัท :",
    "Company Type_": "ประเภทบริษัท<label style='color: red;'>&nbsp;*</label>",
    "Sub-Company Type": "ประเภทบริษัทย่อย",
    "Sub-Company Type-": "ประเภทบริษัทย่อย :",
    "Sub-Company Type_": "ประเภทบริษัทย่อย<label style='color: red;'>&nbsp;*</label>",
    "missing 'Sub-Company Type' field": "กรุณาเลือก 'ประเภทบริษัทย่อย'.",
    "missing 'Company Type' field": "กรุณาเลือก 'ประเภทบริษัท'.",
    "Total Revenue": "รายรับทั้งหมด",
    "Total Expense": "รายจ่ายทั้งหมด",
    "Total Revenue-": "รายรับทั้งหมด :",
    "Total Expense-": "รายจ่ายทั้งหมด :",
    "Confirm this item ?": "ยืนยันรายการนี้ ?",
    "Confirm success.": "ยืนยันสำเร็จ.",
    "Confirm fail": "ยืนยันล้มเหลว. ผู้ใช้รายนี้ได้ยืนยันแล้ว.",
    "Quantity-": "จำนวน :",
    "Quantity": "จำนวน",
    "Quantity_": "จำนวน<label style='color: red;'>&nbsp;*</label>",
    "missing 'Quantity' field": "กรุณากรอก 'จำนวน'.",
    "Unit": "หน่วย",
    "Unit-": "หน่วย :",
    "Unit_": "หน่วย<label style='color: red;'>&nbsp;*</label>",
    "Export Excel": "ดาวน์โหลด Excel",
    "Outstanding": "ยอดค้างชำระ",
    "Paid-Outstanding": "รายรับทั้งสิ้น",
    "Amount/Baht": "จำนวนเงิน/บาท",
    "0001": "เงินคงเหลือเดือนที่แล้ว :",
    "0002": "Profit this month (กำไร-รายรับ เดือนนี้) :",
    "0012": "Profit this month (กำไร-รายรับ เดือนนี้)[USDT] :",
    "0003": "เงินที่ยังเก็บไม่ได้ :",
    "0013": "เงินที่ยังเก็บไม่ได้[USDT] :",
    "0004": "Total this month (รวมค่าใช้จ่ายทั้งหมด เดือนนี้) :",
    "0014": "Total this month (รวมค่าใช้จ่ายทั้งหมด เดือนนี้)[USDT] :",
    "0005": "Net Profit :",
    "0006": "Share Holder :",
    "0007": "พี่วิน 2.5% :",
    "0008": "Share P'Pentor 50% [โอนเงินเข้าเก็บบัญชี PTG] :",
    "0009": "เงินคงเหลือเก็บทั้งหมด เดือนนี้ :",
    "0010": "Share Holder 47.5% [ Snocko ] :",
    "0011": "ทุนหมุนเวียน :",
    "+add image": "+เพิ่มรูปภาพ",
    "+add amount": "+เพิ่มจำนวนเงิน",
    "+add api key": "+เพิ่ม api key",
    "+add system": "+เพิ่มระบบ",
    "+add currency": "+เพิ่มสกุลเงิน",
    "-delete currency": "-ลบสกุลเงิน",
    "-remove": "-นำออก",
    "Total": "ทั้งหมด",
    "Total_": "ทั้งหมด :",
    "Total-": "ทั้งหมด<label style='color: red;'>&nbsp;*</label>",
    "Payment Status": "สถานะการชำระเงิน",
    "Payment": "การชำระเงิน",
    "Payment-": "การชำระเงิน :",
    "Paid": "ชำระเงินแล้ว",
    "Unpaid": "ยังไม่ได้ชำระเงิน",
    "textnumberonly": "กรอกได้เฉพาะตัวเลข (0-9) หรือตัวอักษร (A-Z, a-z) เท่านั้น",
    "numberonly": "กรอกได้เฉพาะตัวเลข (0-9)",
    "textonly": "กรอกได้เฉพาะตัวอักษร (A-Z, a-z, ก-ฮ) เท่านั้น",
    "textTHnumberonly": "กรอกได้เฉพาะตัวเลข (0-9) หรือตัวอักษร (A-Z, a-z, ก-ฮ) เท่านั้น",
    "passwordonly": "รหัสผ่านต้องยาวเกิน 6 ตัวอักษร",
    "Duplicate Username": "ชื่อผู้ใช้ซ้ำ",
    "Duplicate User Role": "บทบาทผู้ใช้ซ้ำ",
    "Duplicate Capital Amount": "จำนวนทุนหมุนเวียนซ้ำ",
    "Duplicate Company Name": "ชื่อบริษัทซ้ำ",
    "Duplicate Company Name(Key)": "ชื่อบริษัท(Key) ซ้ำ",
    "Duplicate Account No.": "เลขที่บัญชีซ้ำ",
    "Duplicate Bill No.": "เลขที่บิลซ้ำ",
    "Duplicate Currency(Short Name)": "สกุลเงินซ้ำ(ชื่อย่อ)",
    "User Role_": "บทบาทผู้ใช้<label style='color: red;'>&nbsp;*</label>",
    "missing 'User Role' field": "กรุณากรอก 'บทบาทผู้ใช้'.",
    "Previous": "ก่อนหน้า",
    "Yesterday": "เมื่อวานนี้",
    "This week": "สัปดาห์นี้",
    "Last week": "สัปดาห์ที่แล้ว",
    "This month": "เดือนนี้",
    "Last month": "เดือนที่แล้ว",
    "Next": "ถัดไป",
    "Today": "วันนี้",
    "Last Week": "อาทิตย์ที่แล้ว",
    "Last Month": "เดือนที่แล้ว",
    "Add System Setting_": "<i class='fas fa-plus mr-1;'></i>เพิ่มการตั้งค่าระบบ",
    "Add System Setting": "เพิ่มการตั้งค่าระบบ",
    "Edit System Setting": "แก้ไขการตั้งค่าระบบ",
    "%": "%",
    "Add system setting success.": "เพิ่มการตั้งค่าระบบสำเร็จ.",
    "Save system setting success.": "บันทึกการตั้งค่าระบบสำเร็จ.",
    "missing 'image file' field": "อัปโหลดไฟล์รูปภาพเท่านั้น",
    "Month-": "เดือน :",
    "Month": "เดือน",
    "January": "มกราคม",
    "February": "กุมภาพันธ์",
    "March": "มีนาคม",
    "April": "เมษายน",
    "May": "พฤษภาคม",
    "June": "มิถุนายน",
    "July": "กรกฎาคม",
    "August": "สิงหาคม",
    "September": "กันยายน",
    "October": "ตุลาคม",
    "November": "พฤศจิกายน",
    "December": "ธันวาคม",
    "Year-": "ปี :",
    "Year": "ปี",
    "Company Management": "การจัดการบริษัท",
    "Bank Management": "การจัดการธนาคาร",
    "Currency Management": "การจัดการสกุลเงิน",
    "Company User Management": "การจัดการผู้ใช้ของบริษัท",
    "Add Company_": "<i class='fas fa-plus mr-1;'></i>เพิ่มบริษัทใหม่",
    "Add Company": "เพิ่มบริษัทใหม่",
    "Edit Company": "แก้ไขบริษัท",
    "Inhouse": "Inhouse",
    "Outhouse": "Outhouse",
    "Add company success.": "เพิ่มบริษัทสำเร็จ.",
    "Edit company success.": "แก้ไขบริษัทสำเร็จ.",
    "Savings Account": "บัญชีเงินฝากออมทรัพย์",
    "Fixed Deposit Account": "บัญชีเงินฝากประจำ",
    "Current Account": "บัญชีเงินฝากกระแสรายวัน หรือบัญชีเงินฝากเดินสะพัด",
    "Crypto Currency": "คริปโทเคอร์เรนซี",
    "continue>": "ดำเนินการต่อ <i class='fas fa-arrow-right mr-1;'></i>",
    "Multiple Slip?": "หลายสลิป?",
    "missing 'continue>' field": "กรุณา 'ดำเนินการต่อ <i class='fas fa-arrow-right mr-1;'></i>'",
    "missing 'Total' field": "ไม่มีข้อมูล 'ทั้งหมด'.",
    "missing 'SlipAmt' field": "กรุณากรอก 'จำนวน' สลิป.",
    "missing 'Same' field": "'ทั้งหมด' และ 'จำนวน' สลิป ไม่ตรงกัน.",
    "Transaction Amount": "จำนวนเงินธุรกรรม",
    "Generate/Edit Bill": "สร้าง/แก้ไข บิล",
    "Add generate bill success.": "สร้างบิลสำเร็จ.",
    "Edit generate bill success.": "แก้ไขบิลสำเร็จ.",
    "Generate Bill": "สร้างบิล",
    "Edit Bill": "แก้ไขบิล",
    "Edit Bill_": "<i class='fas fa-pencil-alt mr-1;'></i> แก้ไขบิล",
    "Generate Bill_": "<i class='fas fa-plus mr-1;'></i> สร้างบิล",
    "Add Description": "เพิ่มคำอธิบาย",
    "Edit Description": "แก้ไขคำอธิบาย",
    "Delete Description": "ลบคำอธิบาย",
    "Delete Description Success.": "ลบคำอธิบายสำเร็จ.",
    "Add Description>": "<i class='fas fa-plus-white mr-1;'></i> เพิ่มคำอธิบาย",
    "Unit/Price": "ราคา/หน่วย",
    "Unit/Price_": "ราคา/หน่วย<label style='color: red;'>&nbsp;*</label>",
    "missing 'Unit/Price' field": "กรุณากรอก 'ราคา/หน่วย'.",
    "Action": "ประเภท",
    "Confirm delete this item ?": "ยืนยันการลบรายการนี้ ?",
    "Delete": "ลบ",
    "BAHT": "บาท",
    "Net Amount": "ยอดเงินสุทธิ",
    "Net Amount_": "ยอดเงินสุทธิ :",
    "Total Price._": "ราคาสุทธิ :",
    "Discount": "ส่วนลด",
    "Discount cash": "ส่วนลดเงินสด",
    "Discount cash_": "ส่วนลดเงินสด :",
    "Discount cash-": "ส่วนลดเงินสด<label style='color: red;'>&nbsp;*</label>",
    "Total after Dis._": "ราคาสุทธิหลังหักส่วนลด :",
    "VAT": "ภาษีมูลค่าเพิ่ม",
    "VAT 7%_": "ภาษีมูลค่าเพิ่ม 7% :",
    "VAT-": "ภาษีมูลค่าเพิ่ม<label style='color: red;'>&nbsp;*</label>",
    "Total Payment": "ยอดชำระทั้งหมด",
    "Total Payment._": "ยอดชำระทั้งหมด :",
    "Total Payment(USDT)._": "ยอดชำระทั้งหมด(USDT) :",
    "missing 'Discount cash' field": "กรุณากรอก 'ส่วนลดเงินสด'.",
    "missing 'Discount' field": "กรุณากรอก 'ส่วนลด'.",
    "missing 'VAT' field": "กรุณากรอก 'ภาษีมูลค่าเพิ่ม'.",
    "Confirm_": "<i class='fas fa-check mr-1;'></i> ยืนยัน",
    "Monthly Fee_": "ค่าเช่ารายเดือน<label style='color: red;'>&nbsp;*</label>",
    "Bill No._": "เลขที่บิล. <label style='color: red;'>&nbsp;*</label>",
    "Bill No.-": "เลขที่บิล. :",
    "Bill No.": "เลขที่บิล.",
    "File Name_": "ชื่อไฟล์ <label style='color: red;'>&nbsp;*</label>",
    "File Name": "ชื่อไฟล์",
    "missing 'Monthly Fee' field": "กรุณากรอก 'ค่าเช่ารายเดือน'.",
    "missing 'Bill No' field": "กรุณากรอก 'เลขที่บิล.'.",
    "missing 'File Name' field": "กรุณากรอก 'ชื่อไฟล์'.",
    "Shareholder": "ตัวแทน",
    "Incorrect Amount, Please try Again.": "จำนวนเงินไม่ถูกต้อง, โปรดลองอีกครั้ง.",
    "Incorrect Date, Please try Again.": "วันที่ไม่ถูกต้อง, โปรดลองอีกครั้ง.",
    "Add shareholder amount success.": "เพิ่มจำนวนเงินตัวแทนสำเร็จ.",
    "Edit shareholder amount success.": "แก้ไขจำนวนเงินตัวแทนสำเร็จ.",
    "Add Shareholder Amount": "เพิ่มจำนวนเงินตัวแทน",
    "Edit Shareholder Amount": "แก้ไขจำนวนเงินตัวแทน",
    "(Key)": "(Key)",
    "url": "url",
    "Item Name_": "ชื่อรายการ<label style='color: red;'>&nbsp;*</label>",
    "missing 'Item Name' field": "กรุณากรอก 'ชื่อรายการ'.",
    "File name for download": "ชื่อไฟล์สำหรับดาวน์โหลด",
    "Download": "ดาวน์โหลด",
    "This month's information is available.": "ข้อมูลของเดือนนี้มีอยู่แล้ว.",
    "This month's data have been confirmed.": "ข้อมูลของเดือนนี้ได้รับการยืนยันแล้ว",
    "This month's report data have been confirmed.": "ข้อมูลรายงานของเดือนนี้ได้รับการยืนยันแล้ว",
    "Overdue Balance": "ยอดค้างชำระ",
    "Overpayment": "ยอดชำระเกิน",
    "Overpayment/Overdue Balance": "ยอดชำระเกิน/ค้างชำระ",
    "Overdue Balance_": "ยอดค้างชำระ",
    "Overdue Balance-": "ยอดค้างชำระ :",
    "Overpayment_": "ยอดชำระเกิน",
    "Overpayment-": "ยอดชำระเกิน :",
    "Overpayment/Overdue Balance_": "ยอดชำระเกิน/ค้างชำระ",
    "Overpay-Outstanding": "ยอดจ่ายเกิน-ค้างชำระ",
    "Transfer Amount": "ยอดโอน",
    "Must be value greater than 0": "ต้องมีค่ามากกว่า 0",
    "Account Type": "ประเภทบัญชี",
    "Account Type_": "ประเภทบัญชี<label style='color: red;'>&nbsp;*</label>",
    "missing 'Account Type' field": "กรุณาเลือก 'ประเภทบัญชี'.",
    "This Report has no data 'Capital Amount'": "รายงานนี้ไม่มีข้อมูล 'จำนวนทุนหมุนเวียน'",
    "This Report has no data 'Shareholder'": "รายงานนี้ไม่มีข้อมูล 'ตัวแทน'",
    "This Report has no data 'Bill'": "รายงานนี้ไม่มีข้อมูล 'บิล'",
    "Cannot add or edit!": "ไม่สามารถ 'เพิ่ม' หรือ 'แก้ไข' ได้!",
    "missing 'Rate - Pay Bill' field": "หากกรอก 'จ่ายบิล' , กรุณากรอก 'Rate'.",
    "missing 'Rate' field": "กรุณากรอก 'Rate'.",
    "missing 'Pay Bill' field": "กรุณากรอก 'จ่ายบิล'.",
    "Incorrect Pay Bill, Please try Again.": "'จ่ายบิล'ไม่ถูกต้อง, โปรดลองอีกครั้ง.",
    "Pay Bill": "จ่ายบิล",
    "Pay Bill-": "จ่ายบิล :",
    "Save pay bill success": "บันทึกการจ่ายบิลสำเร็จ.",
    "Balance Paid": "ยอดจ่ายจริง",
    "Balance Paid_": "ยอดจ่ายจริง :",
    "Company List": "รายชื่อบริษัท",
    "View more": "ดูรายละเอียด",
    "Company Prefix": "Company Prefix",
    "Company Prefix-": "Company Prefix :",
    "Company Prefix_": "Company Prefix <label style='color: red;'>&nbsp;*</label>",
    "List": "รายการ",
    "Add List": "เพิ่มรายการ",
    "Edit List": "แก้ไขรายการ",
    "Add List>": "<i class='fas fa-plus-white mr-1;'></i> เพิ่มรายการ",
    "Delete List": "ลบรายการ",
    "USDT Rate": "USDT Rate",
    "USDT Rate_": "USDT Rate <label style='color: red;'>&nbsp;*</label>",
    "missing 'USDT Rate' field": "กรุณากรอก 'USDT Rate'.",
    "(USDT)": "(USDT)",
    "USDT": "USDT",
    "ยอดแปรผัน": "ยอดแปรผัน",
    "ยอดแปรผัน USDT": "ยอดแปรผัน USDT",
    "Currency": "สกุลเงิน",
    "Currency-": "สกุลเงิน :",
    "(Short Name)": "(ชื่อย่อ)",
    "Edit Currency": "แก้ไขสกุลเงิน",
    "Delete Currency": "ลบสกุลเงิน",
    "Add Currency_": "<i class='fas fa-plus mr-1;'></i>เพิ่มสกุลเงิน",
    "Add Currency": "เพิ่มสกุลเงิน",
    "Currency_": "สกุลเงิน<label style='color: red;'>&nbsp;*</label>",
    "Currency(Short Name)_": "สกุลเงิน(ชื่อย่อ)<label style='color: red;'>&nbsp;*</label>",
    "missing 'Currency' field": "กรุณากรอก 'สกุลเงิน'.",
    "missing 'Currency(Short Name)' field": "กรุณากรอก 'สกุลเงิน(ชื่อย่อ)'.",
    "missing 'Currency(Short Name)-' field": "กรุณาเลือก 'สกุลเงิน(ชื่อย่อ)'.",
    "Add currency success.": "เพิ่มสกุลเงินสำเร็จ.",
    "Edit currency success.": "แก้ไขสกุลเงินสำเร็จ.",
    "Delete currency success.": "ลบสกุลเงินสำเร็จ.",
    "Rate": "Rate",
    "Rate-": "Rate :",
    "Fee_": "ค่าธรรมเนียม :",
    "Fee": "ค่าธรรมเนียม",
    "missing 'Fee' field": "กรุณากรอก 'ค่าธรรมเนียม'.",
    "Cannot Delete": "รายการนี้มีการจ่ายเงินแล้วไม่สามารถลบได้.<br/> กรุณาติดต่อแอดมิน.",

    







    "Data recording failed.": "ข้อมูลไม่ถูกต้อง,  โปรดลองอีกครั้ง.",
};

var Chinese = {
};
