//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace account.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_transaction_detail
    {
        public int id { get; set; }
        public Nullable<int> bill_transaction_id { get; set; }
        public string description { get; set; }
        public Nullable<int> qty { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> is_manual { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> create_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_by { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
        public Nullable<int> delete_by { get; set; }
        public Nullable<decimal> balance_amount { get; set; }
        public Nullable<decimal> overpay { get; set; }
        public Nullable<decimal> complete_amount { get; set; }
        public string discount_description { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<decimal> discount_percent { get; set; }
        public Nullable<int> discount_type { get; set; }
    }
}
