//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace account.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_transaction
    {
        public int id { get; set; }
        public string no { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> month { get; set; }
        public Nullable<int> company_id { get; set; }
        public string company_type_id { get; set; }
        public Nullable<int> company_type_sub_id { get; set; }
        public Nullable<int> company_prefix_id { get; set; }
        public Nullable<int> bill_type { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string file_name { get; set; }
        public string system_bank_id { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public Nullable<decimal> fee { get; set; }
        public Nullable<int> vat { get; set; }
        public Nullable<decimal> vat_amount { get; set; }
        public Nullable<decimal> grand_total { get; set; }
        public Nullable<bool> is_confirm { get; set; }
        public Nullable<System.DateTime> confirm_date { get; set; }
        public Nullable<int> confirm_by { get; set; }
        public Nullable<int> is_complete { get; set; }
        public Nullable<System.DateTime> complete_date { get; set; }
        public string complete_by { get; set; }
        public Nullable<bool> is_done { get; set; }
        public Nullable<System.DateTime> done_date { get; set; }
        public Nullable<int> done_by { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> create_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_by { get; set; }
    }
}
