//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace account.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill_confirm_slip
    {
        public int id { get; set; }
        public Nullable<int> transaction_id { get; set; }
        public string slip { get; set; }
        public string comfirm_by { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<decimal> amount { get; set; }
    }
}
