//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace account.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public int id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> company_type_id { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> create_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_by { get; set; }
        public Nullable<int> in_house { get; set; }
        public Nullable<System.DateTime> action_expire_date { get; set; }
        public Nullable<System.DateTime> action_date { get; set; }
        public Nullable<int> action_by { get; set; }
    }
}
