//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace account.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class accountEntities : DbContext
    {
        public accountEntities()
            : base("name=accountEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bill_transaction> bill_transaction { get; set; }
        public virtual DbSet<bill_transaction_detail> bill_transaction_detail { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<system_user> system_user { get; set; }
        public virtual DbSet<log_pay_member> log_pay_member { get; set; }
        public virtual DbSet<system_currency> system_currency { get; set; }
        public virtual DbSet<user_member_login> user_member_login { get; set; }
    }
}
