//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace account.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_user
    {
        public int id { get; set; }
        public string username { get; set; }
        public Nullable<int> role { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string nickname { get; set; }
        public string mobile { get; set; }
        public string company_name { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> create_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public Nullable<int> update_by { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> login_date { get; set; }
        public Nullable<System.DateTime> logout_date { get; set; }
        public Nullable<bool> is_active { get; set; }
        public Nullable<bool> is_cancel { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
        public Nullable<int> cancel_by { get; set; }
        public Nullable<int> company_id { get; set; }
        public Nullable<int> update_is_active_by { get; set; }
        public Nullable<System.DateTime> update_is_active_date { get; set; }
        public string token_id { get; set; }
        public Nullable<System.DateTime> token_expire_date { get; set; }
    }
}
